version: '3.1'
services:
  dbpostgresql:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=eventListener
      - POSTGRES_USER=eventListener
      - POSTGRES_DB=eventListener
  mongodb:
    image: mongo
    container_name: statistik_db
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_DATABASE=eventListener
      - MONGO_INITDB_ROOT_USERNAME=eventListener
      - MONGO_INITDB_ROOT_PASSWORD=eventListener
